services:
  ichgram:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ichgram
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      CLIENT_URL: http://localhost:5173

  front_ichgram:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: front_ichgram
    # слева порт на твоем компьютере, справа порт внутри контейнера
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: ""
      VITE_PROXY_TARGET: http://ichgram:3000

